# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER EFU

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
COPY humanapiserver.conf /etc/nginx/conf.d/humanapiserver.conf
